---
title: "A2"
author: "Group 10"
date: "9/12/2021"
output: 
  bookdown::pdf_document2:
    toc: yes
    toc_depth: '2'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(visdat)
library(simputation)
library(fastDummies)
```


```{r read_data}
bankruptcy <- readRDS(here::here("data/Bankruptcy.rds"))
```

# Data description

```{r}
vis_miss(bankruptcy)
```



```{r}
bankruptcy %>% 
  dplyr::select_if(is.numeric) %>% 
  GGally::ggpairs()
```

Outliers:

credibiliy:

```{r}
summary(bankruptcy)
```

# Imputation

```{r}
impute_lm(bankruptcy, Liab ~ Assets) %>% 
  impute_lm(Ebit ~ Assets) %>%
  impute_knn(Sales ~ Assets + Ebit + Liab, pool = "univariate", k = 5) %>% 
  impute_knn(Employees ~ Assets + Ebit + Sales, pool = "univariate", k = 5) %>% 
  # impute_lm(DaysIn ~ Assets) %>% 
  separate(SICMajGroup, c("group_code", "group_name"), " ", extra = "merge") %>% 
  mutate(group_code = as.numeric(group_code))-> bankruptcy_imp

bankruptcy_clean <- bankruptcy_imp %>% 
  mutate(group_code = group_code - min(bankruptcy_imp$group_code),
         group_code = as.factor(group_code))
```

`bankruptcy_clean` is the data set after imputation.

# PCA

```{r}
pcaout <- bankruptcy_clean %>% 
  mutate(Name = abbreviate(Name)) %>% 
  column_to_rownames('Name') %>% 
  dplyr::select_if(is.numeric) %>% 
  select(-DaysIn, -EmplUnion, -HeadCourtCityToDE) %>% 
  # select(Assets, CPI, FilingRate, GDP, HeadCityPop, MonthFiled, PrimeFiling, YearFiled) %>%
  prcomp(scale. =TRUE)
```

```{r}
summary(pcaout)
```

```{r}
screeplot(pcaout, type = 'l')
```


```{r}
biplot(pcaout, scale = 0)
```

outliers:




















